name: My first workflow
on: 
  push: 
    branch: master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up php on virtual machine
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      
      - name: Set up sqlite databse
        run: touch database/database.sqlite

      - name: Copy enviromental variables
        run: cp .env.test .env

      - name: Install laravel project 
        run: composer install
      
      - name: Run migrations
        run: php artisan migrate

      - name: Run php static analysis
        run: ./vendor/bin/phpstan analyze

      - name: Run unit tests using phpunit
        run: ./vendor/bin/phpunit

      - name: Connect to VPS
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_KEY: ${{ secrets.DIGITAL_OCEAN_SSH }}
          SSH_USER: ${{ secrets.VPS_USERNAME }}


        