name: My first workflow
on: 
  push: 
    branch: master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up php on virtual machine
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      
      - name: Set up sqlite databse
        run: touch database/database.sqlite

      - name: Copy enviromental variables
        run: cp .env.test .env

      - name: Install laravel project 
        run: composer install
      
      - name: Run migrations
        run: php artisan migrate

      - name: Run php static analysis
        run: ./vendor/bin/phpstan analyze

      - name: Run unit tests using phpunit
        run: ./vendor/bin/phpunit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS
        uses: GPTED/SSH-My-Action@0.1
        with:
          HOST: ${{ secrets.VPS_IP }}
          PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_SSH }}
          USER: ${{ secrets.VPS_USERNAME }}
          CMD: |
            if [ -d "azaman-laravel" ]; then 
              cd azaman-laravel;
              
              git fetch origin master;
              
              git reset --hard origin/master;
              
            else
              git clone https://github.com/iddi5504/azaman-laravel.git;
              cd azaman-laravel;
            fi;   

            chmod +x build.sh;
            ./build.sh;


        